__global mexType *V_x_x_pr,
__global mexType *V_y_x_pr,
__global mexType *V_z_x_pr,
__global mexType *V_x_y_pr,
__global mexType *V_y_y_pr,
__global mexType *V_z_y_pr,
__global mexType *V_x_z_pr,
__global mexType *V_y_z_pr,
__global mexType *V_z_z_pr,
__global mexType *Vx_pr,
__global mexType *Vy_pr,
__global mexType *Vz_pr,
__global mexType *Rxx_pr,
__global mexType *Ryy_pr,
__global mexType *Rzz_pr,
__global mexType *Rxy_pr,
__global mexType *Rxz_pr,
__global mexType *Ryz_pr,
__global mexType *Sigma_x_xx_pr,
__global mexType *Sigma_y_xx_pr,
__global mexType *Sigma_z_xx_pr,
__global mexType *Sigma_x_yy_pr,
__global mexType *Sigma_y_yy_pr,
__global mexType *Sigma_z_yy_pr,
__global mexType *Sigma_x_zz_pr,
__global mexType *Sigma_y_zz_pr,
__global mexType *Sigma_z_zz_pr,
__global mexType *Sigma_x_xy_pr,
__global mexType *Sigma_y_xy_pr,
__global mexType *Sigma_x_xz_pr,
__global mexType *Sigma_z_xz_pr,
__global mexType *Sigma_y_yz_pr,
__global mexType *Sigma_z_yz_pr,
__global mexType *Sigma_xy_pr,
__global mexType *Sigma_xz_pr,
__global mexType *Sigma_yz_pr,
__global mexType *Sigma_xx_pr,
__global mexType *Sigma_yy_pr,
__global mexType *Sigma_zz_pr,
__global mexType *Snapshots_pr,
__global mexType *SourceFunctions_pr,
__global mexType * LambdaMiuMatOverH_pr,
__global mexType * LambdaMatOverH_pr,
__global mexType * MiuMatOverH_pr,
__global mexType * TauLong_pr,
__global mexType * OneOverTauSigma_pr,
__global mexType * TauShear_pr,
__global mexType * InvRhoMatH_pr,
__global mexType * SqrAcc_pr,
__global unsigned int * MaterialMap_pr,
__global unsigned int * SourceMap_pr,
__global mexType * Sigma_xx_zone_pr,
__global mexType * Sigma_yy_zone_pr,
__global mexType * Sigma_zz_zone_pr,
__global mexType * Sigma_xy_zone_pr,
__global mexType * Sigma_xz_zone_pr,
__global mexType * Sigma_yz_zone_pr,
__global mexType * Vx_zone_pr,
__global mexType * Vy_zone_pr,
__global mexType * Vz_zone_pr,
__global mexType * Rxx_zone_pr,
__global mexType * Ryy_zone_pr,
__global mexType * Rzz_zone_pr,
__global mexType * Rxy_zone_pr,
__global mexType * Rxz_zone_pr,
__global mexType * Ryz_zone_pr,
__global unsigned int * MatMap_zone_pr,
__global unsigned int * AllIndexesSparse_pr,
__global unsigned int * AllIndexesLarge_pr,
__global unsigned int * EdgeIndexesSparse_pr,
__global unsigned int * EdgeIndexesLarge_pr,
__global unsigned int * InternalIndexesSparse_pr,
__global unsigned int * InternalIndexesLarge_pr,
__global unsigned int * InternalIndexesSparse_minus1k_pr,
__global unsigned int * InternalIndexesSparse_minus1j_pr,
__global unsigned int * InternalIndexesSparse_minus1i_pr,
__global unsigned int * InternalIndexesSparse_minus2k_pr,
__global unsigned int * InternalIndexesSparse_minus2j_pr,
__global unsigned int * InternalIndexesSparse_minus2i_pr,
__global unsigned int * InternalIndexesSparse_plus1k_pr,
__global unsigned int * InternalIndexesSparse_plus1j_pr,
__global unsigned int * InternalIndexesSparse_plus1i_pr,
__global unsigned int * InternalIndexesSparse_plus2k_pr,
__global unsigned int * InternalIndexesSparse_plus2j_pr,
__global unsigned int * InternalIndexesSparse_plusij_pr,
__global unsigned int * InternalIndexesSparse_plusik_pr,
__global unsigned int * InternalIndexesSparse_plus2i_pr,
__global unsigned int * InternalIndexesSparse_plusjk_pr
